# Generated by Django 4.2 on 2023-05-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_room_host_alter_room_name_message_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='mess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.message'),
        ),
    ]
